[versions]
android_gradle_plugin = "8.2.0"
compose_compiler = "1.5.7"
kotlin = "1.9.21"
ksp = "1.9.21-1.0.16"

[plugins]
android_application = {id = "com.android.application", version.ref = "android_gradle_plugin"}
android_library = {id = "com.android.library", version.ref = "android_gradle_plugin"}
kotlin_android = {id = "org.jetbrains.kotlin.android", version.ref = "kotlin"}
kotlin_jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
#maven_publish = {id = "maven-publish"}
#signing = {id = "signing"}

