[versions]

jsoup = "1.16.1"
okhttp3 = "4.12.0"
paging = "3.2.0"

gson = "2.10"
leakcanary = "2.7"
glide = "4.14.2"
okkv2 = "1.3.5"
junit = "4.13.2"

exoplayer = "2.19.0" # 使用 media 里的
easyplayer2 = "1.3.4"

accompanist = "0.34.0"
navigation_compose = "2.7.7"
coil = "2.5.0"
appcenter = "5.0.4"
commons_text = "1.10.0"
cling = "2.1.2"

compose_lazy_reorder = "0.9.6"

kotlinx_coroutines = "1.7.3"

aria = "3.8.16"
core-ktx = "1.12.0"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"

ffmpeg-kit = "6.0"

ktor = "2.3.3"

jeff_m3u8 = "1.2.0"

moshi = "1.14.0"

koin = "3.5.0"
agp = "8.2.2"
kotlin = "1.9.22"

cybergarage-upnp = "2.1.5"
org-jetbrains-kotlin-jvm = "1.9.22"

bugly = "4.1.9.3"
[libraries]
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
okhttp3_logging_interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }

gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

okkv2 = { module = "com.github.heyanLE.okkv2:okkv2-mmkv", version.ref = "okkv2" }

junit = { module = "junit:junit", version.ref = "junit" }

easyplayer2 = { module = "com.github.easybangumiorg:EasyPlayer2", version.ref = "easyplayer2" }

accompanist_systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist_swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist" }
accompanist_permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

navigtion_compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation_compose" }

coil_compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil_gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

appcenter_analytics = { module = "com.microsoft.appcenter:appcenter-analytics", version.ref = "appcenter" }
appcenter_crashes = { module = "com.microsoft.appcenter:appcenter-crashes", version.ref = "appcenter" }
appcenter_distribute = { module = "com.microsoft.appcenter:appcenter-distribute", version.ref = "appcenter" }

commons_text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }

cling_core = { module = "org.fourthline.cling:cling-core", version.ref = "cling" }
cling_support = { module = "org.fourthline.cling:cling-support", version.ref = "cling" }
compose-reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "compose_lazy_reorder" }

kotlin_coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx_coroutines" }

aria = { module = "me.laoyuyu.aria:core", version.ref = "aria" }
aria_compiler = { module = "me.laoyuyu.aria:compiler", version.ref = "aria" }
aria_m3u8 = { module = "me.laoyuyu.aria:m3u8", version.ref = "aria" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

ffmpeg-kit = { module = "com.arthenica:ffmpeg-kit-full", version.ref = "ffmpeg-kit" }

ktor_core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor_android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }

jeff-m3u8 = { module = "com.github.JeffMony:JeffM3U8Lib", version.ref = "jeff_m3u8" }

moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }


cybergarage-upnp-std = { group = "org.cybergarage.upnp", name = "std", version.ref = "cybergarage-upnp" }
cybergarage-upnp-core = { group = "org.cybergarage.upnp", name = "core", version.ref = "cybergarage-upnp"  }

bugly = {module = "com.tencent.bugly:crashreport", version.ref = "bugly" }
[bundles]
okhttp3 = ["okhttp3", "okhttp3_logging_interceptor"]
cling = ["cling_core", "cling_support"]
appcenter = ["appcenter_analytics", "appcenter_crashes", "appcenter_distribute"]
[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }